version: "2"
services:
  maven:
    image: maven
    container_name: maven
    volumes:
      - /home/nuklo/myapp:/root/myapp
    command: cd /root/myapp && bash -c mvn package myapp
    command: tail -F anything
  java:
    image: openjdk
    command: tail -F anything
    container_name: java
    volumes:
      - /root/myapp
    