version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
      - /usr/bin/docker:/usr/bin/docker
    privileged: true
    command: apt update

  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
    networks:
      - jenkins-net
    command: tail -F anything

networks:
  jenkins-net:

volumes:
  jenkins_home: