---
- name: install pre-requisites 
  ansible.builtin.shell:
    cmd: ansible-galaxy collection install community.docker
- name: clone
  ansible.builtin.git:
    repo: git@github.com:turvik0/javahelloworld.git
    dest: /home/nuklo/myapp
    version: main
- name: deploy Docker Compose stack
  community.docker.docker_compose:
    project_src: ./roles/docker_compose/tasks/dockerfolder
    files:
    - docker-compose.yml
- name: delete files in local folder {{ MYAPPDIRRECTORY }}/myapp
  ansible.builtin.shell:
    cmd: cd {{ MYAPPDIRRECTORY }}/myapp && rm -rf *
- name: docker cp to localhost
  ansible.builtin.shell:
    cmd:  docker cp maven:/root/myapp {{ MYAPPDIRRECTORY }}/myapp
- name: docker cp from localhost to second container
  ansible.builtin.shell:
    cmd:  docker cp {{ MYAPPDIRRECTORY }}/myapp java:/root/myapp
- name: run the project with openjdk
  community.docker.docker_container_exec:
    container: java
    command: java -jar target/gs-maven-0.1.0.jar
    chdir: /root/myapp
  register: result

      
    