---
- name: install pre-requisites 
  ansible.builtin.shell:
    cmd: ansible-galaxy collection install community.docker
- name: clone
  ansible.builtin.git:
    repo: git@github.com:turvik0/javahelloworld.git
    dest: /home/nuklo/myapp
    version: main
- name: deploy Docker Compose stack
  community.docker.docker_compose:
    project_src: ./roles/docker_compose/tasks/dockerfolder
    files:
    - docker-compose.yml

# - name: delete folder {{ MYAPPDIRRECTORY }} # -- no need since volume /home/nuklo/myapp is attahed and is changed in real time with /root/myapp in maven container
#   ansible.builtin.shell:
#     cmd: cd {{ MYAPPDIRRECTORY }}/myapp && rm -rf *
# - name: docker cp to localhost # -- that is the same reason
#   ansible.builtin.shell:
#     cmd:  docker cp maven:/root/myapp {{ MYAPPDIRRECTORY }}

- name: run the project with openjdk
  community.docker.docker_container_exec:
    container: maven
    command: cd /root/myapp && mvn package
    chdir: /root/myapp
  register: result

- name: docker cp from localhost to second container
  ansible.builtin.shell:
    cmd:  docker cp {{ MYAPPDIRRECTORY }}/myapp/ java:/root
- name: run the project with openjdk
  community.docker.docker_container_exec:
    container: java
    command: java -jar target/gs-maven-0.1.0.jar
    chdir: /root/myapp
  register: result

      
    